In [42]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r'C:\Users\Vaishali Tomar\Desktop\ML_masai\bank_data_marketing.csv')
df.head()

age          job  marital          education default  housing     loan  \
0   30  blue-collar  married           basic.9y      no      yes       no   
1   39     services   single        high.school      no       no       no   
2   25     services  married        high.school      no      yes       no   
3   38     services  married           basic.9y      no  unknown  unknown   
4   47       admin.  married  university.degree      no      yes       no   

     campaign     pdays previous     poutcome  emp.var.rate cons.price.idx  \
0  Campaign-2  999-Days        0  nonexistent          -1.8         92.893   
1  Campaign-4  999-Days        0  nonexistent           1.1         93.994   
2  Campaign-1  999-Days        0  nonexistent           1.4         94.465   
3  Campaign-3  999-Days        0  nonexistent           1.4         94.465   
4  Campaign-1  999-Days        0  nonexistent          -0.1           93.2   

   cons.conf.idx pred_subs euribor3m nr.employed  
0          -46.2        no     1.313      5099.1  
1          -36.4        no     4.855        5191  
2          -41.8        no     4.962      5228.1  
3          -41.8        no     4.959      5228.1  
4          -42.0        no     4.191      5195.8

In [44]:
# null value
df.isnull().sum()
# value_count
df['marital'].value_counts()
# columns
df.columns
# datatypes
df.dtypes
# unique_values
df['education'].unique()
# nunique_values
df.nunique()
# fillna
df.fillna(0)
# forward fill
df.fillna(method = "ffill")
# to_numeric
df['cons.price.idx']=pd.to_numeric(df['cons.price.idx'],errors='coerce')
# contains 
df.dropna()[df.dropna()['education'].str.contains('basic.9y')]
# dropna null values
df.dropna().isnull().sum()
# drop cloumns
df.drop(columns =['job'])
print('ok')


ok


In [93]:
# where in data frame
df['age'].where(df['age']>30,0)

0        0
1       39
2        0
3       38
4       47
        ..
4114     0
4115    39
4116     0
4117    58
4118    34
Name: age, Length: 4119, dtype: int64

In [95]:
# argmax 
df['age'].argmax()

AttributeError: 'DataFrame' object has no attribute 'argmax'

In [39]:
# concat and dataframe
A = [1,2,3,43]
col = ['A1']
df = pd.DataFrame({'A1':A})
B = [7,3,5,70]
col = ["B1"]
df2 = pd.DataFrame({"B1":B})
pd.concat([df,df2], axis = 1)

A1  B1
0   1   7
1   2   3
2   3   5
3  43  70

In [49]:
# numpy 
import numpy as np
a = np.random.randint(1,100,15)
a

array([77, 60, 41, 90, 78,  2, 44, 26, 43, 92, 10, 76, 49, 76, 56])

In [48]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[76, 18, 63, 91],
       [44, 19, 90, 86],
       [70, 61, 11, 58],
       [94, 40, 98, 27],
       [40, 58, 22, 14],
       [77, 35,  9,  9]])

In [50]:
# sort 
np.sort(a)

array([ 2, 10, 26, 41, 43, 44, 49, 56, 60, 76, 76, 77, 78, 90, 92])

In [57]:
# sorting all the rows
np.sort(b, axis = 1 )
# sorting all the rows
np.sort(b, axis = 0)


array([[40, 18,  9,  9],
       [44, 19, 11, 14],
       [70, 35, 22, 27],
       [76, 40, 63, 58],
       [77, 58, 90, 86],
       [94, 61, 98, 91]])

In [58]:
#append in 1d
np.append(a,10)

array([77, 60, 41, 90, 78,  2, 44, 26, 43, 92, 10, 76, 49, 76, 56, 10])

In [63]:
#append in 2d
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[76., 18., 63., 91.,  1.],
       [44., 19., 90., 86.,  1.],
       [70., 61., 11., 58.,  1.],
       [94., 40., 98., 27.,  1.],
       [40., 58., 22., 14.,  1.],
       [77., 35.,  9.,  9.,  1.]])

In [75]:
# concatinate and arange

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

np.concatenate((c,d), axis = 0)



[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
# one d in two d
np.expand_dims(a,axis=0)

array([[77, 60, 41, 90, 78,  2, 44, 26, 43, 92, 10, 76, 49, 76, 56]])

In [77]:
# one d in two d
np.expand_dims(a,axis=1)

array([[77],
       [60],
       [41],
       [90],
       [78],
       [ 2],
       [44],
       [26],
       [43],
       [92],
       [10],
       [76],
       [49],
       [76],
       [56]])

In [79]:
# where function give index 
np.where(a>50)

(array([ 0,  1,  3,  4,  9, 11, 13, 14], dtype=int64),)

In [84]:

# replace all valye > 50 with 0


np.where(a>50,0,a)


array([ 0,  0, 41,  0,  0,  2, 44, 26, 43,  0, 10,  0, 49,  0,  0])

In [ ]:
# group by 